"""roulette 包共享常量。"""

QUOTA_CHANNEL_ID = 1545664527410929745
DEFAULT_API_BASE = "https://catiecli.sukaka.top"

PLAYER_COUNT = 5
BET_AMOUNT = 5
FEE_AMOUNT = 1  # 赌大小手续费销毁 1 点
JOIN_TIMEOUT_SECONDS = 120
API_TIMEOUT_SECONDS = 15
COOLDOWN_SECONDS = 10

TRIGGER_KEYWORD = "赌大小"
BANKER_KEYWORD = "当庄家"
BANKER_RUN_KEYWORD = "跑路"
BANKER_MIN_QUOTA = 50  # 当庄家最低额度
BEG_KEYWORD = "乞讨"
BEG_RECEIVE = 5
BEG_COST = 7
BEG_TIMEOUT_SECONDS = 60
BEG_COOLDOWN_SECONDS = 60

DUEL_KEYWORD = "决斗"
DUEL_MIN_QUOTA = 10  # 双方均需 ≥ 10 点才有决斗资格
DUEL_FEE_PERCENT = 20  # 赢家奖金手续费比例（%）
DUEL_TIMEOUT_SECONDS = 60
DUEL_COOLDOWN_SECONDS = 30

RED_PACKET_KEYWORD = "红包"
RED_PACKET_MIN_COST = 10  # 红包最低成本
RED_PACKET_COST_PERCENT = 10  # 红包成本为发送者额度的百分比
RED_PACKET_FEE_PERCENT = 20  # 红包销毁比例（%）
RED_PACKET_MAX_GRABBERS = 8
RED_PACKET_MAX_WINNERS = 3  # 最多 3 人中奖，其余抢 0 点
RED_PACKET_TIMEOUT_SECONDS = 60
RED_PACKET_COOLDOWN_SECONDS = 30

ROB_KEYWORD = "抢劫"
ROB_MIN_QUOTA = 10  # 低于此额度无抢劫能力
ROB_FEE_MIN_PERCENT = 1  # 抢劫成功随机销毁比例下限（%）
ROB_FEE_MAX_PERCENT = 50  # 抢劫成功随机销毁比例上限（%）
ROB_COOLDOWN_SECONDS = 60
ROB_MIN_PERCENT = 10  # 百分比伤害下限（%）
ROB_MAX_PERCENT = 30  # 百分比伤害上限（%）

MARRY_KEYWORD = "结婚"
MARRY_MIN_FEE = 10  # 手续费最低 10 点
MARRY_FEE_PERCENT = 10  # 手续费为两人总额度的百分比
MARRY_TIMEOUT_SECONDS = 60
MARRY_COOLDOWN_SECONDS = 300

CURSE_KEYWORD = "诅咒"
CURSE_COST = 10  # 诅咒费用，全销毁
CURSE_COOLDOWN_SECONDS = 300

ALLIN_KEYWORD = "梭哈"
ALLIN_MIN_QUOTA = 10  # 额度 ≥ 10 点才能梭哈
ALLIN_FEE_PERCENT = 20  # 成功后从奖金扣除的手续费比例（%）
ALLIN_COOLDOWN_SECONDS = 60

LEADERBOARD_KEYWORD = "排行榜"
LEADERBOARD_TOP_N = 10

GACHA_KEYWORD = "抽卡"
GACHA_MIN_COST = 10  # 抽卡最低消耗
GACHA_COST_PERCENT = 10  # 抽卡消耗为额度的百分比
GACHA_COOLDOWN_SECONDS = 10
GACHA_BLANK_CHANCE = 0.5  # 空白卡概率 50%
GACHA_DB = "gacha.db"
GACHA_SEDUCE_SUCCESS_CHANCE = 0.5  # 诱惑成功概率
GACHA_SELFDESTRUCT_MIN_PERCENT = 25  # 自爆销毁比例下限（%）
GACHA_SELFDESTRUCT_MAX_PERCENT = 50  # 自爆销毁比例上限（%）
SEDUCE_KEYWORD = "诱惑"
MY_CARDS_KEYWORD = "我的卡牌"

BANK_KEYWORD = "存钱"
BANK_WITHDRAW_KEYWORD = "取钱"
BANK_BALANCE_KEYWORD = "我的钱"
BANK_MIN_DEPOSIT = 10  # 最低起存金额
BANK_DEPOSIT_PERCENT = 50  # 存入额度比例（%）
BANK_WITHDRAW_MIN_PERCENT = 1  # 取钱扣除比例下限（%）
BANK_WITHDRAW_MAX_PERCENT = 50  # 取钱扣除比例上限（%）
BANK_DB = "bank.db"
BANK_SECURITY_THRESHOLD = 1000  # 存款超过此值解锁普通安保：无法被抢劫
BANK_ROYAL_SECURITY_THRESHOLD = 2000  # 存款超过此值解锁皇家安保：无法被抢劫、诱惑、劫富济贫

BANK_HEIST_KEYWORD = "抢银行"
BANK_HEIST_TEAM_SIZE = 3  # 组队人数
BANK_HEIST_JOIN_TIMEOUT_SECONDS = 60  # 组队 timeout
BANK_HEIST_COOLDOWN_SECONDS = 300  # 个人冷却
BANK_HEIST_TARGET_COOLDOWN_SECONDS = 600  # 目标被抢冷却
BANK_HEIST_MIN_BALANCE = 100  # 目标最低存款
BANK_HEIST_MIN_TARGETS = 1  # 最少目标数
BANK_HEIST_MAX_TARGETS = 3  # 最多目标数
BANK_HEIST_BASE_SUCCESS = 10  # 基础成功率（%）
BANK_HEIST_PROFIT_SHARE = 70  # 队员分配比例（%）
BANK_HEIST_GEAR_NAMES = {"knife": "跑刀", "gun": "起枪", "armor": "全甲"}
BANK_HEIST_GEAR_COST_PERCENT = {"knife": 10, "gun": 50, "armor": 100}  # 装备投入比例（%）
BANK_HEIST_GEAR_MIN_QUOTA = {"knife": 10, "gun": 50, "armor": 100}  # 装备最低额度
BANK_HEIST_GEAR_COEFFICIENTS = {"knife": 1, "gun": 5, "armor": 10}  # 收益系数
BANK_HEIST_GEAR_SUCCESS_BONUS = {"knife": 5, "gun": 15, "armor": 30}  # 成功率加成（%）

RULES_KEYWORD = "规则"

BIG_RED_PACKET_INTERVAL_SECONDS = 360  # 机器人每 6 分钟发一次大红包
BIG_RED_PACKET_POOL = 200  # 奖池 200 点
BIG_RED_PACKET_MAX_GRABBERS = 10  # 最多 10 人参与
BIG_RED_PACKET_MAX_SHARE = 100  # 单人最多抢到 100 点
BIG_RED_PACKET_TIMEOUT_SECONDS = 300  # 5 分钟未满员也开奖
BIG_RED_PACKET_OPTIONS_COUNT = 3  # 人机验证选项数（仅 1 个正确）
