"""roulette 包共享常量。"""

QUOTA_CHANNEL_ID = 1455038454772531311
DEFAULT_API_BASE = "https://catiecli.sukaka.top"

PLAYER_COUNT = 5
BET_AMOUNT = 5
FEE_AMOUNT = 5
JOIN_TIMEOUT_SECONDS = 120
API_TIMEOUT_SECONDS = 15
COOLDOWN_SECONDS = 10

TRIGGER_KEYWORD = "赌大小"
BEG_KEYWORD = "乞讨"
BEG_RECEIVE = 5
BEG_COST = 7
BEG_TIMEOUT_SECONDS = 60
BEG_COOLDOWN_SECONDS = 60

DUEL_KEYWORD = "决斗"
DUEL_BET = 6
DUEL_PRIZE = 10  # 12 - 2 销毁
DUEL_TIMEOUT_SECONDS = 60
DUEL_COOLDOWN_SECONDS = 30

RED_PACKET_KEYWORD = "红包"
RED_PACKET_COST = 10
RED_PACKET_MAX_GRABBERS = 8
RED_PACKET_MAX_WINNERS = 3  # 最多 3 人中奖，其余抢 0 点
RED_PACKET_POOL = 8  # 10 - 2 销毁，随机分给中奖者
RED_PACKET_TIMEOUT_SECONDS = 60
RED_PACKET_COOLDOWN_SECONDS = 30

ROB_KEYWORD = "抢劫"
ROB_MIN_AMOUNT = 1
ROB_MAX_AMOUNT = 10
ROB_MIN_QUOTA = 10  # 低于此额度无抢劫能力
ROB_FEE = 1  # 每次额度交换销毁 1 点
ROB_COOLDOWN_SECONDS = 60

MARRY_KEYWORD = "结婚"
MARRY_FEE = 10  # 手续费销毁
MARRY_TIMEOUT_SECONDS = 60
MARRY_COOLDOWN_SECONDS = 300

CURSE_KEYWORD = "诅咒"
CURSE_COST = 10  # 诅咒费用，全销毁
CURSE_COOLDOWN_SECONDS = 300

ALLIN_KEYWORD = "梭哈"
ALLIN_MIN_QUOTA = 10  # 额度 ≥ 10 点才能梭哈
ALLIN_FEE = 2  # 手续费，全销毁
ALLIN_COOLDOWN_SECONDS = 60

LEADERBOARD_KEYWORD = "排行榜"
LEADERBOARD_TOP_N = 10

GACHA_KEYWORD = "抽卡"
GACHA_COST = 10  # 抽卡消耗 10 点，全销毁
GACHA_COOLDOWN_SECONDS = 10
GACHA_BLANK_CHANCE = 0.5  # 空白卡概率 50%
GACHA_DB = "gacha.db"
GACHA_ROB_MAX_COUNT = 20  # 狂徒/虚弱生效次数
GACHA_SEDUCE_SUCCESS_CHANCE = 0.5  # 诱惑成功概率
SEDUCE_KEYWORD = "诱惑"
MY_CARDS_KEYWORD = "我的卡牌"

BIG_RED_PACKET_INTERVAL_SECONDS = 360  # 机器人每 6 分钟发一次大红包
BIG_RED_PACKET_POOL = 200  # 奖池 200 点
BIG_RED_PACKET_MAX_GRABBERS = 10  # 最多 10 人参与
BIG_RED_PACKET_MAX_SHARE = 100  # 单人最多抢到 100 点
BIG_RED_PACKET_TIMEOUT_SECONDS = 300  # 5 分钟未满员也开奖
BIG_RED_PACKET_OPTIONS_COUNT = 3  # 人机验证选项数（仅 1 个正确）
